const ActionTypes = {
    ///products
  GET_PRODUCTDATA_LOADING: "GET_PRODUCTDATA_LOADING",
  GET_PRODUCTDATA_SUCCESS: "GET_PRODUCTDATA_SUCCESS",
  GET_PRODUCTDATA_FAIL: "GET_PRODUCTDATA_FAIL",

  /// ADD_TO_CART
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_TO_CART: "REMOVE_TO_CART",

  ///SIGN_UP ~ SIGN_IN
  SET_NAME: "SET_NAME",
  SET_EMAIL: "SET_EMAIL",
  SET_PWD: "SET_PWD",
  SET_CONTACT: "SET_CONTACT",
  SET_ADRESS: "SET_ADRESS",
  SET_COUNTRY: "SET_COUNTRY",

  ///CREATE USER
  CREATE_USER_SUCCESS:"CREATE_USER_SUCCESS",
  CREATE_USER_FAILED:"CREATE_USER_FAILED",

  ///LOGIN USER
  LOGIN_USER_SUCCESS:"LOGIN_USER_SUCCESS:",
  LOGIN_USER_FAILED:"LOGIN_USER_FAILED"
}

export default ActionTypes;